######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 100000

actions:

  # Extract data ----
  
  ## Cohort data
  extract_data:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2021-07-01 by month" --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_*.feather
  
  ## Ethnicity      
  extract_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_ethnicity.feather
  
  # Data processing ----
  
  ## Add ethnicity
  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py
    needs: [extract_data, extract_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/data/input*.feather
  
  ## Process data
  data_process:
    run: r:latest analysis/process/process_data.R
    needs: [extract_ethnicity, join_ethnicity]
    outputs:
      moderately_sensitive:
        data: output/data/data_*.rds
        tables: output/data/custom_measures_*.csv
        
 
  # Results ----
  
  ## Figures
  summary_figures:
    run: r:latest analysis/summary_plots.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        plots: output/figures/plot_*.svg
  
  summary_figures_redacted:
    run: r:latest analysis/summary_plots_redacted.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        plots: output/figures/plot*.svg
        
  ## Table 1
  table_1:
    run: r:latest analysis/table_1.R
    needs: [join_ethnicity]
    outputs:
      moderately_sensitive:
        plots: output/tables/table1.html
  



        

