######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 100000

actions:

  # Extract cohort data
  
  ## Learning disability
  generate_ld_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ld --index-date-range "2019-01-01 to 2021-04-01 by month" --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_ld_*.feather
  
  ## Autism
  generate_autism_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_autism --index-date-range "2019-01-01 to 2021-04-01 by month" --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_autism_*.feather
  
  ## Serious Mental Illness
  generate_smi_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_smi --index-date-range "2019-01-01 to 2021-04-01 by month" --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_smi_*.feather
  
  ## Care home
  generate_care_home_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_care_home --index-date-range "2019-01-01 to 2021-04-01 by month" --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_care_home_*.feather
  
  ## Dementia
  generate_dementia_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_dementia --index-date-range "2019-01-01 to 2021-04-01 by month" --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_dementia_*.feather
  
  ## Ethnicity      
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/data --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_ethnicity.feather
        
  
  # Data processing
  
  ## Add ethnicity
  join_ethnicity:
    run: python:latest python analysis/python/scripts/join_ethnicity.py
    needs: [generate_ld_cohort, generate_autism_cohort, generate_smi_cohort, generate_care_home_cohort, generate_dementia_cohort, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/data/input*.feather
        
  
  # Generate measures data
  
  ## Learning disability
  generate_measures_ld:
      run: cohortextractor:latest generate_measures --study-definition study_definition_ld --output-dir=output/data
      needs: [join_ethnicity]
      outputs:
        moderately_sensitive:
          measure_csv: output/data/measure_ld_*.csv
          
  ## Autism
  generate_measures_autism:
      run: cohortextractor:latest generate_measures --study-definition study_definition_autism --output-dir=output/data
      needs: [join_ethnicity]
      outputs:
        moderately_sensitive:
          measure_csv: output/data/measure_autism_*.csv

  ## Serious Mental Illness
  generate_measures_smi:
      run: cohortextractor:latest generate_measures --study-definition study_definition_smi --output-dir=output/data
      needs: [join_ethnicity]
      outputs:
        moderately_sensitive:
          measure_csv: output/data/measure_smi_*.csv

  ## Care home
  generate_measures_care_home:
      run: cohortextractor:latest generate_measures --study-definition study_definition_care_home --output-dir=output/data
      needs: [join_ethnicity]
      outputs:
        moderately_sensitive:
          measure_csv: output/data/measure_care_home_*.csv

  ## Dementia
  generate_measures_dementia:
      run: cohortextractor:latest generate_measures --study-definition study_definition_dementia --output-dir=output/data
      needs: [join_ethnicity]
      outputs:
        moderately_sensitive:
          measure_csv: output/data/measure_dementia_*.csv

  # # Patient to practice lookup
  # generate_study_population_practice_count:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_practice_count --output-dir=output/data
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/data/input_practice_count.csv
  # 
  #         
  # # Practice counts
  # get_practice_count:
  #   run: python:latest python analysis/python/scripts/get_practice_count.py --output-dir=output/data
  #   needs: [generate_study_population_practice_count]
  #   outputs:
  #     moderately_sensitive:
  #       text: output/data/practice_count.json
  # 
  # # Patient counts
  # get_patient_count:
  #   run: python:latest python analysis/python/scripts/get_patients_counts.py --output-dir=output/data
  #   needs: [generate_study_population]
  #   outputs:
  #     moderately_sensitive:
  #       text: output/data/patient_count.json
  #       
  # Measures notebook
  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/python/notebooks/antipsychotics_measures.ipynb --execute --to html --output-dir=/workspace/output/results --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [generate_measures_ld]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/results/antipsychotics_measures.html

#   # Process data
#   data_process:
#     run: r:latest analysis/r/scripts/00_process_data.R
#     needs: [generate_ld_cohort, generate_measures_ld]
#     outputs:
#       highly_sensitive:
#         data: output/data/data_processed.rds
        
  # Data summaries
  data_summaries:
    run: r:latest -e 'rmarkdown::render("analysis/r/markdown/data_summaries.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs: [generate_ld_cohort]
    outputs:
      moderately_sensitive:
        html: output/data_summaries.html
        

